// Master dictionary of ~90 known tech skills used for keyword-based NLP extraction.
// Each entry maps a normalized skill name -> array of text variants to search for.
module.exports = {
  javascript: ["javascript", "js", "es6", "ecmascript"],
  typescript: ["typescript", "ts"],
  python: ["python"],
  java: ["java"],
  "c++": ["c++", "cpp"],
  "c#": ["c#", "csharp"],
  php: ["php"],
  ruby: ["ruby"],
  go: ["golang", "go lang", " go "],
  rust: ["rust"],
  react: ["react.js", "reactjs", "react "],
  "next.js": ["next.js", "nextjs"],
  "vue.js": ["vue.js", "vuejs", "vue "],
  angular: ["angular"],
  redux: ["redux"],
  html: ["html5", "html "],
  css: ["css3", "css "],
  sass: ["sass", "scss"],
  tailwind: ["tailwind", "tailwindcss"],
  bootstrap: ["bootstrap"],
  "node.js": ["node.js", "nodejs", "node "],
  express: ["express.js", "expressjs", "express "],
  django: ["django"],
  flask: ["flask"],
  "spring boot": ["spring boot", "springboot", "spring"],
  ".net": [".net", "dotnet"],
  laravel: ["laravel"],
  mongodb: ["mongodb", "mongo db", "mongo "],
  mysql: ["mysql"],
  postgresql: ["postgresql", "postgres"],
  sqlite: ["sqlite"],
  redis: ["redis"],
  firebase: ["firebase"],
  "rest api": ["rest api", "restful", "rest "],
  graphql: ["graphql"],
  docker: ["docker"],
  kubernetes: ["kubernetes", "k8s"],
  aws: ["aws", "amazon web services"],
  azure: ["azure"],
  gcp: ["gcp", "google cloud"],
  git: ["git "],
  github: ["github"],
  gitlab: ["gitlab"],
  "ci/cd": ["ci/cd", "continuous integration", "continuous deployment"],
  jenkins: ["jenkins"],
  linux: ["linux"],
  nginx: ["nginx"],
  "machine learning": ["machine learning", "ml "],
  "deep learning": ["deep learning"],
  nlp: ["nlp", "natural language processing"],
  tensorflow: ["tensorflow"],
  pytorch: ["pytorch"],
  "scikit-learn": ["scikit-learn", "sklearn"],
  pandas: ["pandas"],
  numpy: ["numpy"],
  opencv: ["opencv"],
  "data analysis": ["data analysis"],
  "data structures": ["data structures"],
  algorithms: ["algorithms"],
  "system design": ["system design"],
  oop: ["oop", "object oriented programming", "object-oriented"],
  agile: ["agile"],
  scrum: ["scrum"],
  jira: ["jira"],
  figma: ["figma"],
  "ui/ux": ["ui/ux", "ui design", "ux design"],
  testing: ["unit testing", "jest", "mocha", "cypress"],
  jest: ["jest"],
  webpack: ["webpack"],
  babel: ["babel"],
  "problem solving": ["problem solving", "problem-solving"],
  communication: ["communication skills", "communication"],
  leadership: ["leadership"],
  teamwork: ["teamwork", "team player", "team collaboration"],
  "project management": ["project management"],
  excel: ["excel", "ms excel"],
  powerbi: ["power bi", "powerbi"],
  tableau: ["tableau"],
  android: ["android"],
  ios: ["ios development", "ios "],
  "react native": ["react native"],
  flutter: ["flutter"],
  swift: ["swift"],
  kotlin: ["kotlin"],
  "spring cloud": ["spring cloud"],
  hibernate: ["hibernate"],
  microservices: ["microservices"],
  "socket.io": ["socket.io", "websocket"],
  "api testing": ["postman", "api testing"],
};
